/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SpacesNewRouteImport } from './routes/spaces/new'
import { Route as SSpaceSlugRouteImport } from './routes/s/$spaceSlug'
import { Route as ApiV1SpacesRouteImport } from './routes/api/v1/spaces'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as SSpaceSlugSettingsMembersRouteImport } from './routes/s/$spaceSlug/settings/members'
import { Route as ApiV1SpacesPromoteRouteImport } from './routes/api/v1/spaces/promote'
import { Route as ApiV1SpacesJoinRouteImport } from './routes/api/v1/spaces/join'
import { Route as ApiElectricShapesSpacesRouteImport } from './routes/api/electric/shapes/spaces'
import { Route as ApiElectricShapesMembershipsRouteImport } from './routes/api/electric/shapes/memberships'
import { Route as ApiV1SpacesSpaceSlugMembersRouteImport } from './routes/api/v1/spaces/$spaceSlug/members'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpacesNewRoute = SpacesNewRouteImport.update({
  id: '/spaces/new',
  path: '/spaces/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SSpaceSlugRoute = SSpaceSlugRouteImport.update({
  id: '/s/$spaceSlug',
  path: '/s/$spaceSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SpacesRoute = ApiV1SpacesRouteImport.update({
  id: '/api/v1/spaces',
  path: '/api/v1/spaces',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SSpaceSlugSettingsMembersRoute =
  SSpaceSlugSettingsMembersRouteImport.update({
    id: '/settings/members',
    path: '/settings/members',
    getParentRoute: () => SSpaceSlugRoute,
  } as any)
const ApiV1SpacesPromoteRoute = ApiV1SpacesPromoteRouteImport.update({
  id: '/promote',
  path: '/promote',
  getParentRoute: () => ApiV1SpacesRoute,
} as any)
const ApiV1SpacesJoinRoute = ApiV1SpacesJoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => ApiV1SpacesRoute,
} as any)
const ApiElectricShapesSpacesRoute = ApiElectricShapesSpacesRouteImport.update({
  id: '/api/electric/shapes/spaces',
  path: '/api/electric/shapes/spaces',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiElectricShapesMembershipsRoute =
  ApiElectricShapesMembershipsRouteImport.update({
    id: '/api/electric/shapes/memberships',
    path: '/api/electric/shapes/memberships',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1SpacesSpaceSlugMembersRoute =
  ApiV1SpacesSpaceSlugMembersRouteImport.update({
    id: '/$spaceSlug/members',
    path: '/$spaceSlug/members',
    getParentRoute: () => ApiV1SpacesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/s/$spaceSlug': typeof SSpaceSlugRouteWithChildren
  '/spaces/new': typeof SpacesNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/spaces': typeof ApiV1SpacesRouteWithChildren
  '/api/electric/shapes/memberships': typeof ApiElectricShapesMembershipsRoute
  '/api/electric/shapes/spaces': typeof ApiElectricShapesSpacesRoute
  '/api/v1/spaces/join': typeof ApiV1SpacesJoinRoute
  '/api/v1/spaces/promote': typeof ApiV1SpacesPromoteRoute
  '/s/$spaceSlug/settings/members': typeof SSpaceSlugSettingsMembersRoute
  '/api/v1/spaces/$spaceSlug/members': typeof ApiV1SpacesSpaceSlugMembersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/s/$spaceSlug': typeof SSpaceSlugRouteWithChildren
  '/spaces/new': typeof SpacesNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/spaces': typeof ApiV1SpacesRouteWithChildren
  '/api/electric/shapes/memberships': typeof ApiElectricShapesMembershipsRoute
  '/api/electric/shapes/spaces': typeof ApiElectricShapesSpacesRoute
  '/api/v1/spaces/join': typeof ApiV1SpacesJoinRoute
  '/api/v1/spaces/promote': typeof ApiV1SpacesPromoteRoute
  '/s/$spaceSlug/settings/members': typeof SSpaceSlugSettingsMembersRoute
  '/api/v1/spaces/$spaceSlug/members': typeof ApiV1SpacesSpaceSlugMembersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/s/$spaceSlug': typeof SSpaceSlugRouteWithChildren
  '/spaces/new': typeof SpacesNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/spaces': typeof ApiV1SpacesRouteWithChildren
  '/api/electric/shapes/memberships': typeof ApiElectricShapesMembershipsRoute
  '/api/electric/shapes/spaces': typeof ApiElectricShapesSpacesRoute
  '/api/v1/spaces/join': typeof ApiV1SpacesJoinRoute
  '/api/v1/spaces/promote': typeof ApiV1SpacesPromoteRoute
  '/s/$spaceSlug/settings/members': typeof SSpaceSlugSettingsMembersRoute
  '/api/v1/spaces/$spaceSlug/members': typeof ApiV1SpacesSpaceSlugMembersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/s/$spaceSlug'
    | '/spaces/new'
    | '/api/auth/$'
    | '/api/v1/spaces'
    | '/api/electric/shapes/memberships'
    | '/api/electric/shapes/spaces'
    | '/api/v1/spaces/join'
    | '/api/v1/spaces/promote'
    | '/s/$spaceSlug/settings/members'
    | '/api/v1/spaces/$spaceSlug/members'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/s/$spaceSlug'
    | '/spaces/new'
    | '/api/auth/$'
    | '/api/v1/spaces'
    | '/api/electric/shapes/memberships'
    | '/api/electric/shapes/spaces'
    | '/api/v1/spaces/join'
    | '/api/v1/spaces/promote'
    | '/s/$spaceSlug/settings/members'
    | '/api/v1/spaces/$spaceSlug/members'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/s/$spaceSlug'
    | '/spaces/new'
    | '/api/auth/$'
    | '/api/v1/spaces'
    | '/api/electric/shapes/memberships'
    | '/api/electric/shapes/spaces'
    | '/api/v1/spaces/join'
    | '/api/v1/spaces/promote'
    | '/s/$spaceSlug/settings/members'
    | '/api/v1/spaces/$spaceSlug/members'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  SSpaceSlugRoute: typeof SSpaceSlugRouteWithChildren
  SpacesNewRoute: typeof SpacesNewRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiV1SpacesRoute: typeof ApiV1SpacesRouteWithChildren
  ApiElectricShapesMembershipsRoute: typeof ApiElectricShapesMembershipsRoute
  ApiElectricShapesSpacesRoute: typeof ApiElectricShapesSpacesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spaces/new': {
      id: '/spaces/new'
      path: '/spaces/new'
      fullPath: '/spaces/new'
      preLoaderRoute: typeof SpacesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$spaceSlug': {
      id: '/s/$spaceSlug'
      path: '/s/$spaceSlug'
      fullPath: '/s/$spaceSlug'
      preLoaderRoute: typeof SSpaceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/spaces': {
      id: '/api/v1/spaces'
      path: '/api/v1/spaces'
      fullPath: '/api/v1/spaces'
      preLoaderRoute: typeof ApiV1SpacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$spaceSlug/settings/members': {
      id: '/s/$spaceSlug/settings/members'
      path: '/settings/members'
      fullPath: '/s/$spaceSlug/settings/members'
      preLoaderRoute: typeof SSpaceSlugSettingsMembersRouteImport
      parentRoute: typeof SSpaceSlugRoute
    }
    '/api/v1/spaces/promote': {
      id: '/api/v1/spaces/promote'
      path: '/promote'
      fullPath: '/api/v1/spaces/promote'
      preLoaderRoute: typeof ApiV1SpacesPromoteRouteImport
      parentRoute: typeof ApiV1SpacesRoute
    }
    '/api/v1/spaces/join': {
      id: '/api/v1/spaces/join'
      path: '/join'
      fullPath: '/api/v1/spaces/join'
      preLoaderRoute: typeof ApiV1SpacesJoinRouteImport
      parentRoute: typeof ApiV1SpacesRoute
    }
    '/api/electric/shapes/spaces': {
      id: '/api/electric/shapes/spaces'
      path: '/api/electric/shapes/spaces'
      fullPath: '/api/electric/shapes/spaces'
      preLoaderRoute: typeof ApiElectricShapesSpacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/electric/shapes/memberships': {
      id: '/api/electric/shapes/memberships'
      path: '/api/electric/shapes/memberships'
      fullPath: '/api/electric/shapes/memberships'
      preLoaderRoute: typeof ApiElectricShapesMembershipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/spaces/$spaceSlug/members': {
      id: '/api/v1/spaces/$spaceSlug/members'
      path: '/$spaceSlug/members'
      fullPath: '/api/v1/spaces/$spaceSlug/members'
      preLoaderRoute: typeof ApiV1SpacesSpaceSlugMembersRouteImport
      parentRoute: typeof ApiV1SpacesRoute
    }
  }
}

interface SSpaceSlugRouteChildren {
  SSpaceSlugSettingsMembersRoute: typeof SSpaceSlugSettingsMembersRoute
}

const SSpaceSlugRouteChildren: SSpaceSlugRouteChildren = {
  SSpaceSlugSettingsMembersRoute: SSpaceSlugSettingsMembersRoute,
}

const SSpaceSlugRouteWithChildren = SSpaceSlugRoute._addFileChildren(
  SSpaceSlugRouteChildren,
)

interface ApiV1SpacesRouteChildren {
  ApiV1SpacesJoinRoute: typeof ApiV1SpacesJoinRoute
  ApiV1SpacesPromoteRoute: typeof ApiV1SpacesPromoteRoute
  ApiV1SpacesSpaceSlugMembersRoute: typeof ApiV1SpacesSpaceSlugMembersRoute
}

const ApiV1SpacesRouteChildren: ApiV1SpacesRouteChildren = {
  ApiV1SpacesJoinRoute: ApiV1SpacesJoinRoute,
  ApiV1SpacesPromoteRoute: ApiV1SpacesPromoteRoute,
  ApiV1SpacesSpaceSlugMembersRoute: ApiV1SpacesSpaceSlugMembersRoute,
}

const ApiV1SpacesRouteWithChildren = ApiV1SpacesRoute._addFileChildren(
  ApiV1SpacesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  SSpaceSlugRoute: SSpaceSlugRouteWithChildren,
  SpacesNewRoute: SpacesNewRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiV1SpacesRoute: ApiV1SpacesRouteWithChildren,
  ApiElectricShapesMembershipsRoute: ApiElectricShapesMembershipsRoute,
  ApiElectricShapesSpacesRoute: ApiElectricShapesSpacesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
